<!DOCTYPE html>
<html lang="hu">
<head>
    <title>Kezdőlap</title>
    <meta charset="UTF-8">
    <meta name="description" content="Egy főiskolai webprojekt, amely az alapvető webfejlesztésről szól. Főként személyes információimat, kedvenc weboldalaimat és órán kapott feladatokat tartalmazza.">
    <meta name="keywords" content="Vass Richárd, iskolai projekt, HTML, CSS, JavaScript">
    <meta name="robots" content="index, follow">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="Hungarian">
    <meta name="author" content="Vass Richárd">
    <link rel="icon" type="image/png" href="assets/svgs/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="assets/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="assets/index.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Uchen&display=swap" rel="stylesheet">
</head>
<body >
    <div id="navbar"></div>
    <div class="mainpage">
        <p class="animate__animated animate__fadeIn welcome">Üdvözöllek az oldalamon!</p>
        <h2 class="date"><?php echo "".date("Y.m.d")?></h2>
    </div>
    <hr>
<script src="assets/themeToggle.js"></script>
<script src="assets/smoothSidebar.js"></script>
<script src="assets/navigationLoad.js"></script>
</body>
<footer>
    <a href="mailto:vassrichard31@gmail.com" target="_blank" class="mailto">Vass Richard, 2024</a>
</footer>
</html>